
package com.epam.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandomService", targetNamespace = "http://service.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RandomService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "randomNumberGenerator", targetNamespace = "http://service.epam.com/", className = "com.epam.service.RandomNumberGenerator")
    @ResponseWrapper(localName = "randomNumberGeneratorResponse", targetNamespace = "http://service.epam.com/", className = "com.epam.service.RandomNumberGeneratorResponse")
    @Action(input = "http://service.epam.com/RandomService/randomNumberGeneratorRequest", output = "http://service.epam.com/RandomService/randomNumberGeneratorResponse")
    public int randomNumberGenerator(
        @WebParam(name = "lowerBound", targetNamespace = "")
        int arg0,
        @WebParam(name = "upperBound", targetNamespace = "")
        int arg1);

}
